version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /tmp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge